#!/bin/bash

echo "🛠  Available Development Scripts"
echo "================================="
echo ""
echo "📁 Location: backend/dev-scripts/"
echo ""
echo "🔐 Authentication Testing:"
echo "   bash backend/dev-scripts/test-auth-manual.sh   - Create test user (check server logs for magic token)"
echo "   bash backend/dev-scripts/test-verify.sh TOKEN  - Verify magic token and test APIs"
echo ""
echo "📚 Documentation:"
echo "   cat backend/dev-scripts/README.md              - Full documentation"
echo ""
echo "💡 Quick Start:"
echo "   1. Start backend: pnpm dev:backend"
echo "   2. Create user:   bash backend/dev-scripts/test-auth-manual.sh"
echo "   3. Check server logs for magic token"
echo "   4. Verify token:  bash backend/dev-scripts/test-verify.sh <magic_token>"
echo ""
