name: Auto Delete Branch After Merge

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Delete merged branch
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = context.payload.pull_request.head.ref;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Don't delete protected branches
            const protectedBranches = ['main', 'master', 'develop', 'staging', 'production'];

            if (protectedBranches.includes(branchName)) {
              console.log(`⚠️ Branch "${branchName}" is protected. Skipping deletion.`);
              return;
            }

            // Only delete if the branch is in the same repo (not a fork)
            if (context.payload.pull_request.head.repo.full_name !== context.payload.pull_request.base.repo.full_name) {
              console.log(`⚠️ Branch "${branchName}" is from a fork. Skipping deletion.`);
              return;
            }

            try {
              await github.rest.git.deleteRef({
                owner,
                repo,
                ref: `heads/${branchName}`
              });
              console.log(`✅ Successfully deleted branch: ${branchName}`);
            } catch (error) {
              console.log(`❌ Failed to delete branch "${branchName}": ${error.message}`);
            }
